# This is a basic workflow to help you get started with Actions

name: trigger repo D bump

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [workflow_dispatch]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: dispatch trigger parent(s) repo bump
        run: |
          curl -X POST https://api.github.com/repos/billypchan/carthageDummyD/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.E_SECRET }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
           
          curl -X POST https://api.github.com/repos/billypchan/carthageDummyD/actions/workflows/workflowDispatchRecceiver.yaml/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -H "Content-Type: application/json" \
          -H "Authorization: token ${{secrets.WORKFLOW_ACTIONS_TOKEN}}"
          --data '{"ref": "main"}'
           
